import Image from 'next/image';
import React from 'react';


export const metadata = {
  title: "rEzeAn Next App",
  description: "Generated by create next app",
};


const AboutPages = () => {
    return (
        <div className='text-center'>
            <h2>About us / I am a Rezwan from Dumurgacha, nakaihat gobindoganj,Gaibandha, Rangpur,Bangladesh.</h2>

<Image src='/rkr.png' width={300} height={400} alt='rezwan images'></Image>
            
<Image src='/slute.jpeg' width={300} height={400} alt='images'></Image>
            

        </div>
    );
};

export default AboutPages;